alwaysaddtrackers: true
autostart: true
disableipv6: false
disabletrackers: false
donecmd: ""
donecmdthreshold: 30s
downloaddirectory: /var/lib/cloud
downloadrate: Unlimited
enableseeding: true
enableupload: true
enginedebug: false
incomingport: 50007
muteenginelog: true
obfspreferred: true
obfsrequirepreferred: false
proxyurl: ""
rssurl: ""
scraperurl: https://raw.githubusercontent.com/boypt/simple-torrent/master/scraper-config.json
seedratio: 1.5
trackerlisturl: https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt
uploadrate: High
watchdirectory: ""
